name: treinamento-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.0.5
  - backcall=0.2.0
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - colorama=0.4.6
  - comm=0.1.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - executing=0.8.3
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - ipykernel=6.28.0
  - ipython=8.12.2
  - jedi=0.18.1
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - libffi=3.4.4
  - libsodium=1.0.18
  - matplotlib-inline=0.1.6
  - nest-asyncio=1.5.6
  - openssl=3.0.12
  - packaging=23.1
  - parso=0.8.3
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=3.10.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - python=3.8.18
  - python-dateutil=2.8.2
  - pywin32=305
  - pyzmq=25.1.0
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tk=8.6.12
  - tornado=6.3.3
  - traitlets=5.7.1
  - typing_extensions=4.7.1
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - wheel=0.41.2
  - xz=5.4.5
  - zeromq=4.3.4
  - zipp=3.17.0
  - zlib=1.2.13
  - pip:
      - absl-py==2.0.0
      - astunparse==1.6.3
      - cachetools==5.3.2
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - contourpy==1.1.1
      - cycler==0.12.1
      - filelock==3.13.1
      - flatbuffers==23.5.26
      - fonttools==4.47.0
      - fsspec==2023.12.2
      - gast==0.4.0
      - google-auth==2.26.1
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.60.0
      - h5py==3.10.0
      - idna==3.6
      - importlib-resources==6.1.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - keras==2.13.1
      - kiwisolver==1.4.5
      - libclang==16.0.6
      - markdown==3.5.1
      - markupsafe==2.1.3
      - matplotlib==3.7.4
      - mpmath==1.3.0
      - networkx==3.1
      - numpy==1.24.3
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - pandas==2.0.3
      - pillow==10.2.0
      - protobuf==4.25.1
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pyparsing==3.1.1
      - pytz==2023.3.post1
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.13.1
      - sympy==1.12
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.13.0
      - tensorflow-estimator==2.13.0
      - tensorflow-intel==2.13.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.4.0
      - threadpoolctl==3.2.0
      - torch==2.1.2
      - torchvision==0.16.2
      - typing-extensions==4.5.0
      - tzdata==2023.4
      - urllib3==2.1.0
      - werkzeug==3.0.1
      - wrapt==1.16.0
